/hri_person_manager:
  ros__parameters:
    match_threshold: 0.5 # Minimum likelihood to associate a face/body/voice to a given person
    reference_frame: 'map' # This should usually be a static frame wrt to the robot
    robot_reference_frame: 'base_link' # Reference frame for persons' distance computation
    personal_distance: 1.2 # Person upper distance threshold for personal zone (the nearest one) (m)
    social_distance: 3.6 # Person distance threshold between personal (nearer) and social (farther) zone (m)
    public_distance: 20. # Person distance threshold between social (nearer) and public (farther) zone (m)
